{% set version = "1.1.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-c3net
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/c3net_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/c3net/c3net_{{ version }}.tar.gz
  sha256: ee2232545e0f1a051a259d69db0fee479c60bfb98b1bc41af67ca218af361476

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-igraph
  run:
    - r-base
    - r-igraph

test:
  commands:
    - $R -e "library('c3net')"           # [not win]
    - "\"%R%\" -e \"library('c3net')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=c3net
  license: GPL-3.0-or-later
  summary: This package allows inferring gene regulatory networks with direct physical interactions from microarray expression data using C3NET.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
