travis:
  secure:
    BINSTAR_TOKEN: jijfUQrMHOwzSLckrjGwUYK/oPe6n6k4So7LeJWIhgqLO5uwpJUJGRZA6weCnUHOiC0WQt4PtxqpScVR/CocjaqF3zq9JDk3zALqhbEfWoBcosfT+5TSI87DBZi07vbynQSx1r9Ra119DJhF5lYjFUyY2tPqRSsH3q7ZQujLMrtrqN/V+V9LRQeJwuJn+3Y5uKH6TlWKGCWIqAglopdWKSnhOwTXT+TMEB4Hi8eyf0nq0aAoAsAxsPPBSeN6UYjndgXI1X0ncJWa19bH28PENX4C8dS5MSIfpTwlQgh3fF3/XzHD/359sMY92uKJazb1+5BmEQRcY9OyjxKrEEHmGZKJBg+gUAv21suqHw5Zst81oVdk9GQfjgVbYhTHwc3Ju569C8Q6vN2VQmW9RFsoee/GR54+e8l+uri4Ut815mhTXdfP6RPMtVi3p1iKhA0kFZScUbnjc61/PMyRY/veD78RYwQiivlApfRABp/YMU4MGze6R8hScTFBNe3nqgMv7gHQ04gLKxj+4F50USlmxHb78dYJb0+wTNLXHxomqRpQKFdn9zsQ8f4oxOnF9qEVD8iAyYjDZJfhXPtW2QZ/pDDSX5/03b5W+hoHAkkiBxG9I02ELacXKBWa1n/Lp6vYo7FaZ/bxL2cOeJJMo+4JrkgwS63suFSbg2nZX1CO3Kc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
