appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: opsnv/LYpQa3nWw1dFtpAxe2IcGdPwBiFBvBIt5ll9KB3G6D93iBk190yMfblIFp5YI1S/+VvzUKqpWIfV8T66fxGz/d8OEEkukO9Zl4MknwZ0h9E9kJNz3BssJ3X+hhx85IDwkT6vJECBOFBFd3i50tLn7mxUKU8PAe+wPTHg+hnqkzWkO/tLz4ogZ1HsJRsEJjTNMTKaDXyTPZZQxlzSheevnUH7xrBEP30ySPexsWMPgsbm+DwhByLYLWqvLywMDvBZLMJEkfquyJf0h/t+rWAwu5uzPDMH1S3mKPYEsAK0aFzoTJ4Mhc6RYnEblHp05h7ievOVSgapyyVNIBcOn9tqX69fNUxFVpk0Q2v4Fle7vY7RoBOCZr2hTUMlqk+N+r8+R3nygjdYxpP3mlSslZTSdVOvAytvWQkJz6pm6z37AhTAIxkZtsfrSp6TpKPAg5fGs9jMGXMgrCEHHLP7HEUn+7qFwV62WFamZxiUfXY3StHcIYuHgIlgBc7tvxFhMjlpOrLPVOa8asviEn3JIB8aarnN7Fgh2D3QoFCquQtwtmcMSTt4TwlZAHOl3xeISRfaH1PWfBMztPe8kJY8CzGJeW9YRYD2eqGQeIDkOVCGb+kYbQx8Oh8Zy5ZnVrDRGdmC3VHxAwmHFGiF0yBAz4iVrwOlekMJKodMrCi80=}
bot:
  automerge: true
